version: '3.8'

services:
  # Для локальной разработки открываем порты: backend, db postgres, для prod - только через nginx

  auth-nginx:
    ports:
      - ${FRONTEND_PORT:-80}:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./docker/nginx/configs:/etc/nginx/conf.d:rw

  auth-backend:
    ports:
      - ${BACKEND_PORT:-8001}:8001
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ./src/app:/opt/app
    command: poetry run python3 main.py

  auth-postgres:
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  auth-redis:
    ports:
      - ${REDIS_PORT:-6379}:6379

  auth-jaeger:
    ports:
      - ${JAEGER_PORT:-16686}:16686
      - ${JAEGER_UDP_PORT:-6831}:6831/udp
