name: Code check
on: [push]

jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest

    steps:
    - name: "Клонирование репозитория"
      uses: actions/checkout@v3

    - name: "Установка python"
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Установка Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
        virtualenvs-path: .venv

    - name: "Установка зависимостей"
      run: poetry install --no-root --only dev || true

    - name: "Запуск линтеров"
      run: |
        poetry run flake8 ./src
        poetry run mypy ./src
        poetry run black --check ./src
        poetry run isort --check ./src
